# Generated by Django 2.2.4 on 2019-12-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Cód')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('code', models.CharField(auto_created=True, blank=True, max_length=25, verbose_name='Cód')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(auto_created=True, max_length=25, verbose_name='Cód')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='account.Profile')),
                ('careers', models.ManyToManyField(blank=True, to='school.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, max_length=25, unique=True, verbose_name='Cód')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('subject_type', models.CharField(choices=[('STARTER', 'STARTER'), ('BASIC', 'BASIC'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=12, verbose_name='Nível')),
                ('professors', models.ManyToManyField(blank=True, to='school.Professor')),
                ('students', models.ManyToManyField(blank=True, to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='mm/dd/yy', verbose_name='Data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Inserida em')),
                ('grade', models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '9'), ('10', '10')], max_length=2, verbose_name='Nota')),
                ('grade_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='students',
            field=models.ManyToManyField(blank=True, to='school.Student'),
        ),
        migrations.AddField(
            model_name='career',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='school.Subject'),
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='mm/dd/yy', verbose_name='Data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('absence', models.CharField(choices=[('.5', '0.5'), ('01', '1')], max_length=2, verbose_name='Ausencia')),
                ('absence_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
        ),
    ]
