# Generated by Django 2.2.4 on 2019-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='time',
            field=models.TimeField(default='11:00', verbose_name='Horário'),
        ),
    ]
