# Generated by Django 2.2.4 on 2019-12-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_career_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='Turma', max_length=25, unique=True, verbose_name='Tipo Ensino'),
        ),
    ]
