# Generated by Django 2.2.4 on 2019-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20191201_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='code',
            field=models.CharField(default='Grupo', max_length=25, unique=True, verbose_name='Tipo Ensino'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='Turma', max_length=25, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=12, verbose_name='Nível'),
        ),
    ]
