# Generated by Django 2.2.4 on 2019-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20191201_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.TimeField(default='11:00', verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código'),
        ),
    ]
