# Generated by Django 2.2.4 on 2019-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191201_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('STARTER', 'STARTER'), ('BASIC', 'BASIC'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=12, verbose_name='Nível'),
        ),
    ]
