# Generated by Django 2.2.4 on 2019-12-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20191201_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='students',
        ),
    ]
