# Generated by Django 2.2.4 on 2019-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_career_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='code',
            field=models.CharField(default='Grupo', max_length=25, verbose_name='Tipo Ensino'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(choices=[('SEG-QUA', 'SEG-QUA'), ('TER-QUI', 'TER-QUI'), ('SEXTA-2h', 'SEXTA-2h'), ('SÁBADO-2h', 'SÁBADO-2h')], max_length=80, verbose_name='Dias da semana'),
        ),
    ]
