# Generated by Django 2.2.4 on 2019-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20191201_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Cód'),
        ),
    ]
