# Generated by Django 2.2.4 on 2019-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20191201_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.CharField(default='10:00/11:00', max_length=30, verbose_name='Horário'),
        ),
    ]
